### ISSUE TITLE
not updating when I fork

### ISSUE THREAD

**Issue by bthooper** [learn-co-curriculum/js-advanced-scope-closures-lab#13]
For some reason, I forked this lab and completed it.

However, the fork indicator does not seem to recognize that I forked it, even though the test passing indicator and the submit indicator have turned green...

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @bthooper.

We have updated the materials and this issue should no longer occur. However, since you have already forked this lesson, learn.co may not display the updated lesson. If you would like to get the green lights to correctly reflect completion, save your code solution in a separate location, delete your forked copy
of this repo and revisit the lesson on learn.co. This should trigger learn.co to provide you with the
updated lesson and allow you to paste in your previous solution and register completion.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
